[package]
name = "bg3modmanager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.23", features = ["derive"] }
lz4_flex = "0.11.1"
md5 = "0.7.0"
xmltree = "0.10.3"
